openapi: '3.1.1'
info:
  title: Free-Grilly
  version: '25.3.27'
  description: The local Free-Grilly api

externalDocs:
  url: https://github.com/epiecs/free-grilly
  description: Git repository

servers:
  - url: http://{free-grilly-ip}/api
    variables:
      free-grilly-ip:
        default: 192.168.200.10
        description: Your Free-Grilly ip address

tags:
  - name: grill
    description: Grill overview with current status and temperatures
  - name: probes
    description: Probes
  - name: settings
    description: Setting management

components:
  schemas:
    Grill:
      type: object
      properties:
        name:
          type: string
          example: Free-Grilly
          description: The chosen grill name
        unique_id:
          type: string
          format: uuid
          example: 12abc3de-4567-89f0-a123-456b789012c3
          description: The unique id in UUIDv4 format
        firmware_version:
          type: string
          format: yy.mm.dd
          example: 25.3.1
          description: The current firmware version in CalVer
        battery_percentage:
          type: integer
          example: 95
          description: The current - estimated - battery %
        battery_charging:
          type: boolean
          example: true
          description: If the battery is charging
        wifi_connected:
          type: boolean
          example: true
          description: If the grill is connected to a wifi network
        wifi_ssid:
          type: string
          example: my-home-wifi
          description: The name of the wifi network that the grill is connected to
        wifi_signal:
          type: integer
          format: -dbm
          example: -61
          description: The wifi signal expressed in dbm. The closer to 0 the better.
        wifi_ip:
          type: string
          example: 192.168.0.10
          description: The wifi ip when connected to your network
        probes:
          type: array
          minItems: 8
          maxItems: 8
          items:
            type: object
            properties:
              probe_id:
                type: integer
                description: The number of the probe
              temperature:
                type: 
                  - "number"
                  - "null"
                format: float
                description: The temperature in Celcius
              target_temperature:
                type: 
                  - "number"
                  - "null"
                format: float
                description: The target temperature in Celcius
              connected:
                type: boolean
                description: Is the probe connected
            example:
              - probe_id: 1
                temperature: 23.71832
                target_temperature: 23.71832
                connected: true
              - probe_id: 2
                temperature: null
                target_temperature: null
                connected: false
              - probe_id: 3
                temperature: 110.12578
                target_temperature: 110.12578
                connected: true
              - probe_id: 4
                temperature: 250.12578
                target_temperature: 250.12578
                connected: true
              - probe_id: 5
                temperature: null
                target_temperature: null
                connected: false
              - probe_id: 6
                temperature: null
                target_temperature: null
                connected: false
              - probe_id: 7
                temperature: null
                target_temperature: null
                connected: false
              - probe_id: 8
                temperature: null
                target_temperature: null
                connected: false
    
    Probe:
      type: object
      properties:
        probe_id:
          type: integer
          description: The number of the probe
          readOnly: true
        temperature:
          type: 
            - "number"
            - "null"
          format: float
          readOnly: true
          description: The temperature in Celcius
        target_temperature:
          type: 
            - "number"
            - "null"
          format: float
          description: The target temperature in Celcius
        connected:
          type: boolean
          description: Is the probe connected
          readOnly: true
        probe_type:
          type: string
          description: >
            The probe type connected to the grilleye. There are several built-in probe types. If 
            you have the spec sheet of your probe you can try and setup a custom probe and provide 
            the values. Not all probes will work so YMMV.
          example: GRILLEYE_IRIS
          default: GRILLEYE_IRIS
          $ref:  "#/components/schemas/probe_type"
        reference_kohm:
          type: 
            - "number"
            - "null"
          format: float
          example: 100
          default: 100
          description: The reference resistance value from the spec sheet in kOhm - only used with type CUSTOM
        reference_celcius:
          type: 
            - "number"
            - "null"
          format: float
          example: 25
          default: 25
          description: The reference celcius value from the spec sheet - only used with type CUSTOM
        reference_beta:
          type: 
            - "number"
            - "null"
          format: float
          examples: 
            - 4250
            - null
          default: 4250
          description: The reference beta coefficient value from the spec sheet - only used with type CUSTOM
        
    
    Settings:
      type: object
      properties:
        name:
          type: string
          example: Free-Grilly
          description: The chosen grill name
        unique_id:
          type: string
          format: uuid
          example: 12abc3de-4567-89f0-a123-456b789012c3
          description: The unique id in UUIDv4 format
          readOnly: true
        firmware_version:
          type: string
          format: yy.mm.dd
          example: 25.3.1
          description: The current firmware version in CalVer
          readOnly: true
        wifi_ssid:
          type: string
          example: my-home-wifi
          description: The name of the wifi network that the grill is connected to
        wifi_password:
          type: string
          example: "********"
          description: The wifi password.
          writeOnly: true
        wifi_ip:
          type: string
          example: 192.168.0.10
          description: The wifi ip when connected to your network
        wifi_subnet:
          type: string
          example: 255.255.255.0
          description: The wifi subnet
        wifi_gateway:
          type: string
          example: 192.168.0.1
          description: The wifi gateway
        wifi_dns:
          type: string
          example: 9.9.9.9
          description: The wifi dns
        local_ap_ssid:
          type: string
          example: FreeGrilly
          description: The name of the grill's local wifi network
        local_ap_password:
          type: string
          example: "********"
          description: The local wifi password
          writeOnly: true
        local_ap_ip:
          type: string
          example: 192.168.200.10
          description: The local wifi ip
        local_ap_subnet:
          type: string
          example: 255.255.255.0
          description: The local wifi subnet
        local_ap_gateway:
          type: string
          example: 192.168.200.1
          description: The local wifi gateway

    ##
    # Enums
    ##
    probe_type:
      type: string
      example: GRILLEYE_IRIS
      enum:
        - CUSTOM
        - GRILLEYE_IRIS
        - IKEA_FANTAST

paths:
  /grill:
    get:
      tags:
        - grill
      summary: Current grill info and probes
      description: >
        Get the current needed basic grill information + all the probes and 
        their temperatures
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Grill'
  
  /probes:
    get:
      tags:
        - probes
      summary: Probes
      description: >
        View current probe settings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                minItems: 8
                maxItems: 8
                items:
                  $ref: '#/components/schemas/Probe'
    post:
      tags:
        - probes
      summary: Probes
      description: >
        Edit probes
      requestBody:
        required: true
        description: Settings to set
        content:
            application/json:
              schema:
                type: array
                minItems: 8
                maxItems: 8
                items:
                  $ref: '#/components/schemas/Probe'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                minItems: 8
                maxItems: 8
                items:
                  $ref: '#/components/schemas/Probe'
  
  /settings:
    get:
      tags:
        - settings
      summary: Grill settings
      description: >
        Endpoint to view current settings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Settings'
    post:
      tags:
        - settings
      summary: Grill settings
      description: >
        Endpoint to edit settings
      requestBody:
        required: true
        description: Settings to set
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Settings'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Settings'
                